### ISSUE TITLE
images on gallery page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#11]
some images look warped in the thumbnail view. 

this is going to be a grueling task, but take all the images that look warped as a thumbnail and crop them to look non-warped. 

the main image (the one that pops up after you click the thumbnail) will remain the same, just the thumbnail needs to be re-cropped to prevent that warped look. 

due:
8-8-15   3p

**Comment by vanderbeam** [comment]
Done.

**Comment by rodneystrong** [comment]
Unfortunately this doesn't seem to be done. I checked the gh-pages url and they are still warped  : (

**Comment by vanderbeam** [comment]
This is really weird. My local copy won't push. I'll figure it out.

**Comment by vanderbeam** [comment]
Done

**Comment by rodneystrong** [comment]
*nods 

in situations like this, if you haven't figured it out within 40 - 90min (no, those aren't arbitrary numbers, they are taken from scientific research), then hit me up and i'll gladly help.

**Comment by rodneystrong** [comment]
Good job on figuring out the pushing issue! 

Unfortunately I'm still seeing a few images that are warped. Please go through the gallery again and fix the images. After my quick browse I saw at least 10 thumbnails that still needed fixing.

**Comment by vanderbeam** [comment]
Phew! Think I got em all.

**Comment by rodneystrong** [comment]
good job! thanks for keepin at it ;)
